### ISSUE TITLE
dct and idct are the same formula?

### ISSUE THREAD

**Issue by yuan243212790** [denpo1022/Image-Transform-DCT-and-IDCT#1]

**Comment by denpo1022** [comment]
Hi @yuan243212790 , actually they are not the same formula.

Here the DCT formula:
![image](https://user-images.githubusercontent.com/30108508/177249995-585581f1-8010-4b35-a033-ea67f5b1f6b0.png)

and the IDCT one:
![image](https://user-images.githubusercontent.com/30108508/177250782-ac8f8243-b45f-4dc8-974f-b9a5f26b9b24.png)

If you replace **C(i)**, **C(j)** above with **C(u)**, **C(v)** then you can understand [the code](https://github.com/denpo1022/Image-Transform-DCT-and-IDCT/blob/31f20bdd03a61cf03e11bb4f388a615093d6c34c/main.py#L15) more easily.

**Comment by yuan243212790** [comment]
can you tell me what the differences?just exchange f(X,Y) and D(X,Y)

**Comment by denpo1022** [comment]
@yuan243212790 Maybe explain with the code will be better:

One of the differences you should watch out is the position where calculating **_C(i) C(j)_** ( `Cu` `Cv` in the code).
For **DCT**, calculate **_C(i) C(j)_** right after the first nested `for` loop (means before double Σ in the formula).
https://github.com/denpo1022/Image-Transform-DCT-and-IDCT/blob/31f20bdd03a61cf03e11bb4f388a615093d6c34c/main.py#L17-L28
For **IDCT**, the calculation is located after second nested `for` loop (means after double Σ in the formula).
https://github.com/denpo1022/Image-Transform-DCT-and-IDCT/blob/31f20bdd03a61cf03e11bb4f388a615093d6c34c/main.py#L51-L67
Also be careful with the variables name I used in the nested `for` loop.
(In **DCT** outer nested `for` loop uses `u` and `v`, inner one uses `x` and `y`. In **IDCT** outer nested `for` loop uses `x` and `y`, inner one uses `u` and `v`)

**Comment by yuan243212790** [comment]
I know what you mean, but I mean that these ci cj are constants, and the calculation method is essentially the same，just exchange F and f







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月6日(星期三) 下午5:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [denpo1022/Image-Transform-DCT-and-IDCT] dct and idct are the same formula? (Issue #1)





 
@yuan243212790 Maybe explain with the code will be better:
 
One of the differences you should watch out is the position where calculating C(i) C(j) ( Cu Cv in the code).
 For DCT, calculate C(i) C(j) right after the first nested for loop (means before double Σ in the formula).
 https://github.com/denpo1022/Image-Transform-DCT-and-IDCT/blob/31f20bdd03a61cf03e11bb4f388a615093d6c34c/main.py#L17-L28
 For IDCT, the calculation is located after second nested for loop (means after double Σ in the formula).
 https://github.com/denpo1022/Image-Transform-DCT-and-IDCT/blob/31f20bdd03a61cf03e11bb4f388a615093d6c34c/main.py#L51-L67
 Also be careful with the variables name I used in the nested for loop.
 (In DCT outer nested for loop uses u and v, inner one uses x and y. In IDCT outer nested for loop uses x and y, inner one uses u and v)

**Comment by denpo1022** [comment]
I won't call them exactly the same but yes the basic idea and concept of the both formulas are pretty similar.
For me it's more clear to treat DCT and IDCT as distinct formulas, but now I understand your opinion and the way of thinking.
Regarding DCT and IDCT as the same would be fine, just be careful when implementing with the code :D

**Comment by yuan243212790** [comment]
Thank you very much！I just want to know the implement in code are the same，Only one is the operation of the original image, and the other is the post-processing of the former




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月6日(星期三) 晚上6:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [denpo1022/Image-Transform-DCT-and-IDCT] dct and idct are the same formula? (Issue #1)





 
I won't call them exactly the same but yes the basic idea and concept of the both formulas are pretty similar.
 For me it's more clear to treat DCT and IDCT as distinct formulas, but now I understand your opinion and the way of thinking.
 Regarding DCT and IDCT as the same would be fine, just be careful when implementing with the code :D

**Comment by denpo1022** [comment]
> Thank you very much！I just want to know the implement in code are the same，Only one is the operation of the original image, and the other is the post-processing of the former
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2022年7月6日(星期三) 晚上6:41 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [denpo1022/Image-Transform-DCT-and-IDCT] dct and idct are the same formula? (Issue #1) I won't call them exactly the same but yes the basic idea and concept of the both formulas are pretty similar. For me it's more clear to treat DCT and IDCT as distinct formulas, but now I understand your opinion and the way of thinking. Regarding DCT and IDCT as the same would be fine, just be careful when implementing with the code :D — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

No problem. You can always launch a new issue whenever you got something want to ask.
